[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "baselines"
version = "0.1.0"
authors = [{ name = "Yicheng Luo", email = "ethanluoyc@gmail.com" }]
requires-python = ">=3.9"
