name: 'build'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: pdm cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # - name: Setup PDM
      #   uses: pdm-project/setup-pdm@v3
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     pdm-version: 2.10.0
      #     cache: true
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/corax/corax-devcontainer
          cacheFrom: ghcr.io/corax/corax-devcontainer
          # Change this to be your CI task/script
          runCmd: |
            # Add multiple commands to run if needed
            export TFDS_DATA_DIR=$PWD/.tensorflow_datasets
            mkdir -p $TFDS_DATA_DIR
            pdm config cache_dir .cache/pdm
            pdm install -G:all
            pdm lint
            pdm test
            export TFDS_DATA_DIR=$PWD/.tensorflow_datasets
            pdm run tfds build --config v1-medium-replay d4rl_mujoco_halfcheetah
            ls -l $TFDS_DATA_DIR
