name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository_owner }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pdm cache
        uses: actions/cache@v3
        with:
          path: .cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-
      - name: TFDS cache
        uses: actions/cache@v3
        with:
          path: .tensorflow_datasets
          key: ${{ runner.os }}-tfds-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-tfds-
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/corax/corax-devcontainer
          cacheFrom: ghcr.io/corax/corax-devcontainer
          # Change this to be your CI task/script
          runCmd: |
            # Add multiple commands to run if needed
            export TFDS_DATA_DIR=$PWD/.tensorflow_datasets
            mkdir -p $TFDS_DATA_DIR
            pdm config cache_dir .cache/pdm
            pdm install -G:all
            pdm lint
            pdm test
            pdm run python projects/baselines/baselines/iql/train_test.py
